site_name: AOliverio Docs
site_url: http://www.aoliverio.com
site_description: Projects documentation with Markdown.
site_author: Antonio Oliverio

repo_url: https://github.com/aoliverio/docs-repository/
theme: flatly

pages:
- Home: index.md
- Projects:
    - Builder: builder.md
    - Builder extensions: builder-extensions.md