site_name: AOliverio Docs
site_url: http://www.aoliverio.com
site_description: Projects documentation with Markdown.
site_author: Antonio Oliverio

repo_url: https://github.com/aoliverio/docs-repository/

pages:
- Home: index.md
- Rapid Application Development:
    - Overview: builder-overview.md
    - Builder: builder.md
    - Extensions: builder-extensions.md